### ISSUE TITLE
CSS-də teqləri və class, id adlarını bir-birinin ardınca yazarkən vergüldən istifadə etmək lazımdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Sevinj-joy/Sevinj-joy-PragmatechFoundationProject#7]
Belə yazılış yanlışdır, çünki teqlərin arasında vergül işarəsi qoymaq lazımdır. :x:

```css
h1 h2 h3 h4 h5 {
    margin: 0px;
    padding: 0px;
}
```

Belə yazılış düzgündür. :heavy_check_mark:

```css
h1,
h2,
h3,
h4,
h5 {
  margin: 0px;
  padding: 0px;
}
```
